#!/bin/bash

# thanks to https://lists.gnu.org/archive/html/bug-bash/2007-09/msg00004.html for history tips

blue="\033[38;2;135;206;235m"
reg="\033[0m"
prompt=$(printf "${blue}todo: >  $reg")

todo list
echo

while :
do
	# read command
	read -e -p "$prompt" cmd
	case "$cmd" in
		# no command, do nothing
		'')
			: ;;
		# exit, then exit
		exit)
			clear -x; exit ;;
		# anything else, add to history and execute
		*)
			history -s "$cmd"
			xargs todo <<< $cmd
			echo ;;
	esac
done


